output:
  sort-results: true

linters-settings:
  dogsled:
    max-blank-identifiers: 2

  dupl:
    threshold: 150

  errcheck:
    check-type-assertions: true
    check-blank: true

  exhaustive:
    check:
      - switch
      - map
    check-generated: true
    default-signifies-exhaustive: true

  gocognit:
    min-complexity: 15

  paralleltest:
    ignore-missing-subtests: true

  varnamelen:
    max-distance: 10

    ignore-names:
      - i
      - id
      - sb
      - to
      - tt
      - w

  testifylint:
    disable:
      - require-error

  revive:
    rules:
      - name: dot-imports
        arguments:
          - allowedPackages:
            - "github.com/ch-schulz/htmfunc/element"
            - "github.com/ch-schulz/htmfunc/attribute"
            - "github.com/ch-schulz/htmfunc/flow"

  stylecheck:
    checks:
      - all
      - -ST1003




linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    - exportloopref
    - gci
    - gofumpt
    - ireturn
    - nlreturn
    - noctx
    - testpackage
    - tparallel
    - wrapcheck