output:
  sort-results: true

linters-settings:
  dogsled:
    max-blank-identifiers: 2

  dupl:
    threshold: 150

  errcheck:
    check-type-assertions: true
    check-blank: true

  exhaustive:
    check:
      - switch
      - map
    check-generated: true
    default-signifies-exhaustive: true

  gocognit:
    min-complexity: 15

  paralleltest:
    ignore-missing-subtests: true

  varnamelen:
    max-distance: 10

    ignore-names:
      - tt
      - w
      - i
      - to

  ireturn:
    allow:
      - Element
      - error

  testifylint:
    disable:
      - require-error

  revive:
    rules:
      - name: dot-imports
        arguments:
          - allowedPackages:
            - "github.com/ch-schulz/htmfunc/element"



linters:
  enable-all: false
  disable-all: true
  enable:
    - bidichk
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - dupword
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - godot
    - godox
    - gofmt
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosimple
    - gosmopolitan
    - govet
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - ireturn
    - lll
    - makezero
    - mirror
    - misspell
    - nilerr
    - nilnil
    - mnd
    - nolintlint
    - paralleltest
    - perfsprint
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tenv
    - testableexamples
    - testifylint
    - thelper
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - varnamelen
    - wastedassign
    - wsl
    - zerologlint