version: '3'

shopt: [ -s globstar ]

tasks:
  install:
    # Install build tools, getting away from 'go get -tool' for the moment, as it clutters go.mod.
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install golang.org/x/vuln/cmd/govulncheck@latest
    sources:
      - taskfile.yml

  check:
    cmds:
      - go test ./...
      - golangci-lint run --fast-only --output.tab.path stdout --output.tab.print-linter-name --output.tab.colors
    sources:
      - ./**/*.go
      - taskfile.yml
      - .golangci.yml
      - go.mod
      - go.sum

  check+:
    cmds:
      - task test
      - task vulncheck
      - golangci-lint fmt
      - golangci-lint run --output.tab.path stdout --output.tab.print-linter-name --output.tab.colors
    sources:
      - ./**/*.go
      - taskfile.yml
      - .golangci.yml
      - go.mod
      - go.sum

  test:
    cmds:
      - go test ./... -count 1000 -race
    sources:
      - ./**/*.go
      - taskfile.yml

  vulncheck:
    cmds:
      - govulncheck ./...
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
      - taskfile.yml
      - .golangci.yml

  generate:
    cmds:
      - cd internal && go run .

  deps:
    cmds:
      - go get -u ./...
      - go mod tidy
      - go mod vendor
    sources:
      - ./**/*.go
      - go.mod
      - taskfile.yml
      - .golangci.yml