version: '3'

shopt: [ -s globstar ]

tasks:
  check:
    cmds:
      - go test ./...
      - go tool golangci-lint run --fast-only --output.tab.path stdout --output.tab.print-linter-name --output.tab.colors
    sources:
      - ./**/*.go
      - taskfile.yml
      - .golangci.yml
      - go.mod
      - go.sum

  check+:
    cmds:
      - task test
      - task vulncheck
      - go tool golangci-lint fmt
      - go tool golangci-lint run --output.tab.path stdout --output.tab.print-linter-name --output.tab.colors
    sources:
      - ./**/*.go
      - taskfile.yml
      - .golangci.yml
      - go.mod
      - go.sum

  test:
    cmds:
      - go test ./... -count 1000 -race
    sources:
      - ./**/*.go
      - taskfile.yml

  vulncheck:
    cmds:
      - go tool govulncheck ./...
    sources:
      - ./**/*.go
      - go.mod
      - go.sum
      - taskfile.yml
      - .golangci.yml

  deps:
    cmds:
      - go get -u ./...
      - go mod tidy
      - go mod vendor
    sources:
      - ./**/*.go
      - go.mod
      - taskfile.yml
      - .golangci.yml
