package attributes

type MethodParamName struct {
	FuncName, paramName string
}

var mappings = map[string]MethodParamName{ //nolint:gochecknoglobals
	"abbr":                            {"AbbrAttribute", "abbr"}, // Avoid name collision with abbr element
	"accept-charset":                  {"AcceptCharset", "acceptCharset"},
	"accesskey":                       {"AccessKey", "accessKey"},
	"allowfullscreen":                 {"AllowFullScreen", "allowFullScreen"},
	"autocapitalize":                  {"AutoCapitalize", "autoCapitalize"},
	"autocomplete":                    {"AutoComplete", "autoComplete"},
	"autocorrect":                     {"AutoCorrect", "autoCorrect"},
	"autofocus":                       {"AutoFocus", "autoFocus"},
	"autoplay":                        {"AutoPlay", "autoPlay"},
	"charset":                         {"CharSet", "charSet"},
	"cite":                            {"CiteAttribute", "cite"}, // Avoid name collision with cite element
	"closedby":                        {"ClosedBy", "closedBy"},
	"colorspace":                      {"ColorSpace", "colorSpace"},
	"colspan":                         {"ColSpan", "colSpan"},
	"commmandfor":                     {"CommandFor", "commandFor"},
	"contenteditable":                 {"ContentEditable", "contentEditable"},
	"coords":                          {"Coords", "coords"},
	"crossorigin":                     {"CrossOrigin", "crossOrigin"},
	"data":                            {"DataAttribute", "data"}, // Avoid name collision with data element
	"datetime":                        {"DateTime", "dateTime"},
	"defer":                           {"Defer", "deferV"}, // defer must be renamed to avoid conflict with defer key word
	"dirname":                         {"DirName", "dirName"},
	"enctype":                         {"EncType", "encType"},
	"enterkeyhint":                    {"EnterKeyHint", "enterKeyHint"},
	"fetchpriority":                   {"FetchPriority", "fetchPriority"},
	"for":                             {"For", "forV"},           // for must be renamed to avoid conflict with defer key word
	"form":                            {"FormAttribute", "form"}, // Avoid name collision with form element
	"formaction":                      {"FormAction", "formAction"},
	"formenctype":                     {"FormEnctype", "formEnctype"},
	"formmethod":                      {"FormMethod", "formMethod"},
	"formnovalidate":                  {"FormNoValidate", "formNoValidate"},
	"formtarget":                      {"FormTarget", "formTarget"},
	"href":                            {"HRef", "hRef"},
	"hreflang":                        {"HRefLang", "hRefLang"},
	"http-equiv":                      {"HttpEquiv", "httpEquiv"},
	"imagesizes":                      {"ImageSizes", "imageSizes"},
	"imagesrcset":                     {"ImageSrcSet", "imageSrcSet"},
	"inputmode":                       {"InputMode", "inputMode"},
	"ismap":                           {"IsMap", "isMap"},
	"itemid":                          {"ItemId", "itemId"},
	"itemprop":                        {"ItemProp", "itemProp"},
	"itemref":                         {"ItemRef", "itemRef"},
	"itemscope":                       {"ItemScope", "itemScope"},
	"itemtype":                        {"ItemType", "itemType"},
	"label":                           {"LabelAttribute", "label"}, // Avoid name collision with label element
	"maxlength":                       {"MaxLength", "maxLength"},
	"minlength":                       {"MinLength", "minLength"},
	"nomodule":                        {"NoModule", "noModule"},
	"nonce":                           {"Nonce", "nonce"},
	"novalidate":                      {"NoValidate", "noValidate"},
	"placeholder":                     {"PlaceHolder", "placeHolder"},
	"playsinline":                     {"PlaysInline", "playsInline"},
	"popover":                         {"PopOver", "popOver"},
	"popovertarget":                   {"PopOverTarget", "popOverTarget"},
	"popovertargetaction":             {"PopOverTargetAction", "popOverTargetAction"},
	"preload":                         {"PreLoad", "preLoad"},
	"readonly":                        {"ReadOnly", "readOnly"},
	"referrerpolicy":                  {"ReferrerPolicy", "referrerPolicy"},
	"rowspan":                         {"RowSpan", "rowSpan"},
	"sandbox":                         {"SandBox", "sandBox"},
	"shadowrootclonable":              {"ShadowRootClonable", "shadowRootClonable"},
	"shadowrootcustomelementregistry": {"ShadowRootCustomElementRegistry", "shadowRootCustomElementRegistry"},
	"shadowrootdelegatesfocus":        {"ShadowRootDelegatesFocus", "shadowRootDelegatesFocus"},
	"shadowrootmode":                  {"ShadowRootMode", "shadowRootMode"},
	"shadowrootserializable":          {"ShadowRootSerializable", "shadowRootSerializable"},
	"slot":                            {"SlotAttribute", "slot"}, // Avoid name collision with slot element
	"span":                            {"SpanAttribute", "span"}, // Avoid name collision with span element
	"spellcheck":                      {"SpellCheck", "spellCheck"},
	"srcdoc":                          {"SrcDoc", "srcDoc"},
	"srclang":                         {"SrcLang", "srcLang"},
	"srcset":                          {"SrcSet", "srcSet"},
	"style":                           {"StyleAttribute", "style"}, // Avoid name collision with style element
	"tabindex":                        {"TabIndex", "tabIndex"},
	"title":                           {"TitleAttribute", "title"}, // Avoid name collision with title element
	"type":                            {"Type", "typeV"},           // type must be renamed to avoid conflict with type key word
	"usemap":                          {"UseMap", "useMap"},
	"writingsuggestions":              {"WritingSuggestions", "writingSuggestions"},
	"onafterprint":                    {"OnAfterPrint", "onAfterPrint"},
	"onauxclick":                      {"OnAuxClick", "onAuxClick"},
	"onbeforeinput":                   {"OnBeforeInput", "onBeforeInput"},
	"onbeforematch":                   {"OnBeforeMatch", "onBeforeMatch"},
	"onbeforeprint":                   {"OnBeforePrint", "onBeforePrint"},
	"onbeforeunload":                  {"OnBeforeUnload", "onBeforeUnload"},
	"onbeforetoggle":                  {"OnBeforeToggle", "onBeforeToggle"},
	"onblur":                          {"OnBlur", "onBlur"},
	"oncancel":                        {"OnCancel", "onCancel"},
	"oncanplay":                       {"OnCanPlay", "onCanPlay"},
	"oncanplaythrough":                {"OnCanplayThrough", "onCanplayThrough"},
	"onchange":                        {"OnChange", "onChange"},
	"onclick":                         {"OnClick", "onClick"},
	"onclose":                         {"OnClose", "onClose"},
	"oncommand":                       {"OnCommand", "onCommand"},
	"oncontextlost":                   {"OnContextLost", "onContextLost"},
	"oncontextmenu":                   {"OnContextMenu", "onContextMenu"},
	"oncontextrestored":               {"OnContextRestored", "onContextRestored"},
	"oncopy":                          {"OnCopy", "onCopy"},
	"oncuechange":                     {"OnCueChange", "onCueChange"},
	"oncut":                           {"OnCut", "onCut"},
	"ondblclick":                      {"OnDblClick", "onDblClick"},
	"ondrag":                          {"OnDrag", "onDrag"},
	"ondragend":                       {"OnDragEnd", "onDragEnd"},
	"ondragenter":                     {"OnDragEnter", "onDragEnter"},
	"ondragleave":                     {"OnDragLeave", "onDragLeave"},
	"ondragover":                      {"OnDragOver", "onDragOver"},
	"ondragstart":                     {"OnDragStart", "onDragStart"},
	"ondrop":                          {"OnDrop", "onDrop"},
	"ondurationchange":                {"OnDurationChange", "onDurationChange"},
	"onemptied":                       {"OnEmptied", "onEmptied"},
	"onended":                         {"OnEnded", "onEnded"},
	"onerror":                         {"OnError", "onError"},
	"onfocus":                         {"OnFocus", "onFocus"},
	"onformdata":                      {"OnFormData", "onFormData"},
	"onhashchange":                    {"OnHashChange", "onHashChange"},
	"oninput":                         {"OnInput", "onInput"},
	"oninvalid":                       {"OnInvalid", "onInvalid"},
	"onkeydown":                       {"OnKeyDown", "onKeyDown"},
	"onkeypress":                      {"OnKeyPress", "onKeyPress"},
	"onkeyup":                         {"OnKeyUp", "onKeyUp"},
	"onlanguagechange":                {"OnLanguageChange", "onLanguageChange"},
	"onload":                          {"OnLoad", "onLoad"},
	"onloadeddata":                    {"OnLoadedData", "onLoadedData"},
	"onloadedmetadata":                {"OnLoadedMetaData", "onLoadedMetaData"},
	"onloadstart":                     {"OnLoadStart", "onLoadStart"},
	"onmessage":                       {"OnMessage", "onMessage"},
	"onmessageerror":                  {"OnMessageError", "onMessageError"},
	"onmousedown":                     {"OnMouseDown", "onMouseDown"},
	"onmouseenter":                    {"OnMouseEnter", "onMouseEnter"},
	"onmouseleave":                    {"OnMouseLeave", "onMouseLeave"},
	"onmousemove":                     {"OnMouseMove", "onMouseMove"},
	"onmouseout":                      {"OnMouseOut", "onMouseOut"},
	"onmouseover":                     {"OnMouseOver", "onMouseOver"},
	"onmouseup":                       {"OnMouseUp", "onMouseUp"},
	"onoffline":                       {"OnOffline", "onOffline"},
	"ononline":                        {"OnOnline", "onOnline"},
	"onpagehide":                      {"OnPageHide", "onPageHide"},
	"onpagereveal":                    {"OnPageReveal", "onPageReveal"},
	"onpageshow":                      {"OnPageShow", "onPageShow"},
	"onpageswap":                      {"OnPageSwap", "onPageSwap"},
	"onpaste":                         {"OnPaste", "onPaste"},
	"onpause":                         {"OnPause", "onPause"},
	"onplay":                          {"OnPlay", "onPlay"},
	"onplaying":                       {"OnPlaying", "onPlaying"},
	"onpopstate":                      {"OnPopState", "onPopState"},
	"onprogress":                      {"OnProgress", "onProgress"},
	"onratechange":                    {"OnRatechange", "onRatechange"},
	"onreset":                         {"OnReset", "onReset"},
	"onresize":                        {"OnResize", "onResize"},
	"onrejectionhandled":              {"OnRejectionHandled", "onRejectionHandled"},
	"onscroll":                        {"OnScroll", "onScroll"},
	"onscrollend":                     {"OnScrollEnd", "onScrollEnd"},
	"onsecuritypolicyviolation":       {"OnSecurityPolicyViolation", "onSecurityPolicyViolation"},
	"onseeked":                        {"OnSeeked", "onSeeked"},
	"onseeking":                       {"OnSeeking", "onSeeking"},
	"onselect":                        {"OnSelect", "onSelect"},
	"onslotchange":                    {"OnSlotChange", "onSlotChange"},
	"onstalled":                       {"OnStalled", "onStalled"},
	"onstorage":                       {"OnStorage", "onStorage"},
	"onsubmit":                        {"OnSubmit", "onSubmit"},
	"onsuspend":                       {"OnSuspend", "onSuspend"},
	"ontimeupdate":                    {"OnTimeUpdate", "onTimeUpdate"},
	"ontoggle":                        {"OnToggle", "onToggle"},
	"onunhandledrejection":            {"OnUnhandledRejection", "onUnhandledRejection"},
	"onunload":                        {"OnUnload", "onUnload"},
	"onvolumechange":                  {"OnVolumeChange", "onVolumeChange"},
	"onwaiting":                       {"OnWaiting", "onWaiting"},
	"onwheel":                         {"onWheel", "onWheel"},
}
